/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppPublicarRouteImport } from './routes/app.publicar'
import { Route as AppParametrizacionRouteImport } from './routes/app.parametrizacion'
import { Route as AppPanelAdminRouteImport } from './routes/app.panel-admin'
//import { Route as AppNotificacionesRouteImport } from './routes/app.notificaciones'
import { Route as AppInicioRouteImport } from './routes/app.inicio'
import { Route as AppGestionDocumentosRouteImport } from './routes/app.gestion-documentos'
import { Route as AppDocumentosRouteImport } from './routes/app.documentos'
import { Route as AppDocumentoIdRouteImport } from './routes/app.documento.$id'
import { Route as AppDocumentoIdEditarRouteImport } from './routes/app.documento.$id.editar'
import { Route as AppDocumentoIdActualizarRouteImport } from './routes/app.documento.$id.actualizar'
import { Route as AppCambiarContrasenaRouteImport } from './routes/app.cambiar-contrasena'


const AppRoute = AppRouteImport.update({
    id: '/app',
    path: '/app',
    getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AppRoute,
} as any)
const AppPublicarRoute = AppPublicarRouteImport.update({
    id: '/publicar',
    path: '/publicar',
    getParentRoute: () => AppRoute,
} as any)
const AppParametrizacionRoute = AppParametrizacionRouteImport.update({
    id: '/parametrizacion',
    path: '/parametrizacion',
    getParentRoute: () => AppRoute,
} as any)
const AppPanelAdminRoute = AppPanelAdminRouteImport.update({
    id: '/panel-admin',
    path: '/panel-admin',
    getParentRoute: () => AppRoute,
} as any)
/*const AppNotificacionesRoute = AppNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => AppRoute,
} as any)*/
const AppInicioRoute = AppInicioRouteImport.update({
    id: '/inicio',
    path: '/inicio',
    getParentRoute: () => AppRoute,
} as any)
const AppGestionDocumentosRoute = AppGestionDocumentosRouteImport.update({
    id: '/gestion-documentos',
    path: '/gestion-documentos',
    getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AppRoute,
} as any)
const AppDocumentoIdRoute = AppDocumentoIdRouteImport.update({
    id: '/documento/$id',
    path: '/documento/$id',
    getParentRoute: () => AppRoute,
} as any)
const AppDocumentoIdEditarRoute = AppDocumentoIdEditarRouteImport.update({
    id: '/documento/$id/editar',
    path: '/documento/$id/editar',
    getParentRoute: () => AppRoute,
} as any)
const AppDocumentoIdActualizarRoute = AppDocumentoIdActualizarRouteImport.update({
    id: '/documento/$id/actualizar',
    path: '/documento/$id/actualizar',
    getParentRoute: () => AppRoute,
} as any)
const AppCambiarContrasenaRoute = AppCambiarContrasenaRouteImport.update({
    id: '/cambiar-contrasena',
    path: '/cambiar-contrasena',
    getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute
    '/app': typeof AppRouteWithChildren
    '/app/documentos': typeof AppDocumentosRoute
    '/app/gestion-documentos': typeof AppGestionDocumentosRoute
    '/app/inicio': typeof AppInicioRoute
    //'/app/notificaciones': typeof AppNotificacionesRoute
    '/app/panel-admin': typeof AppPanelAdminRoute
    '/app/parametrizacion': typeof AppParametrizacionRoute
    '/app/publicar': typeof AppPublicarRoute
    '/app/usuarios': typeof AppUsuariosRoute
    '/app/cambiar-contrasena': typeof AppCambiarContrasenaRoute
    '/app/documento/$id': typeof AppDocumentoIdRoute
    '/app/documento/$id/editar': typeof AppDocumentoIdEditarRoute
    '/app/documento/$id/actualizar': typeof AppDocumentoIdActualizarRoute
}
export interface FileRoutesByTo {
    '/': typeof IndexRoute
    '/app': typeof AppRouteWithChildren
    '/app/documentos': typeof AppDocumentosRoute
    '/app/gestion-documentos': typeof AppGestionDocumentosRoute
    '/app/inicio': typeof AppInicioRoute
    //'/app/notificaciones': typeof AppNotificacionesRoute
    '/app/panel-admin': typeof AppPanelAdminRoute
    '/app/parametrizacion': typeof AppParametrizacionRoute
    '/app/publicar': typeof AppPublicarRoute
    '/app/usuarios': typeof AppUsuariosRoute
    '/app/cambiar-contrasena': typeof AppCambiarContrasenaRoute
    '/app/documento/$id': typeof AppDocumentoIdRoute
    '/app/documento/$id/editar': typeof AppDocumentoIdEditarRoute
    '/app/documento/$id/actualizar': typeof AppDocumentoIdActualizarRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/': typeof IndexRoute
    '/app': typeof AppRouteWithChildren
    '/app/documentos': typeof AppDocumentosRoute
    '/app/gestion-documentos': typeof AppGestionDocumentosRoute
    '/app/inicio': typeof AppInicioRoute
   // '/app/notificaciones': typeof AppNotificacionesRoute
    '/app/panel-admin': typeof AppPanelAdminRoute
    '/app/parametrizacion': typeof AppParametrizacionRoute
    '/app/publicar': typeof AppPublicarRoute
    '/app/usuarios': typeof AppUsuariosRoute
    '/app/cambiar-contrasena': typeof AppCambiarContrasenaRoute
    '/app/documento/$id': typeof AppDocumentoIdRoute
    '/app/documento/$id/editar': typeof AppDocumentoIdEditarRoute
    '/app/documento/$id/actualizar': typeof AppDocumentoIdActualizarRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
        | '/'
        | '/app'
        | '/app/documentos'
        | '/app/gestion-documentos'
        | '/app/inicio'
   //     | '/app/notificaciones'
        | '/app/panel-admin'
        | '/app/parametrizacion'
        | '/app/publicar'
        | '/app/usuarios'
        | '/app/cambiar-contrasena'
        | '/app/documento/$id'
        | '/app/documento/$id/editar'
    fileRoutesByTo: FileRoutesByTo
    to:
        | '/'
        | '/app'
        | '/app/documentos'
        | '/app/gestion-documentos'
        | '/app/inicio'
     //   | '/app/notificaciones'
        | '/app/panel-admin'
        | '/app/parametrizacion'
        | '/app/publicar'
        | '/app/usuarios'
        | '/app/cambiar-contrasena'
        | '/app/documento/$id'
        | '/app/documento/$id/editar'
        | '/app/documento/$id/actualizar'
    id:
        | '__root__'
        | '/'
        | '/app'
        | '/app/documentos'
        | '/app/gestion-documentos'
        | '/app/inicio'
    //    | '/app/notificaciones'
        | '/app/panel-admin'
        | '/app/parametrizacion'
        | '/app/publicar'
        | '/app/usuarios'
        | '/app/cambiar-contrasena'
        | '/app/documento/$id'
        | '/app/documento/$id/editar'
        | '/app/documento/$id/actualizar'
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute
    AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/app': {
            id: '/app'
            path: '/app'
            fullPath: '/app'
            preLoaderRoute: typeof AppRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/': {
            id: '/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof IndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/app/usuarios': {
            id: '/app/usuarios'
            path: '/usuarios'
            fullPath: '/app/usuarios'
            preLoaderRoute: typeof AppUsuariosRouteImport
            parentRoute: typeof AppRoute
        }
        '/app/publicar': {
            id: '/app/publicar'
            path: '/publicar'
            fullPath: '/app/publicar'
            preLoaderRoute: typeof AppPublicarRouteImport
            parentRoute: typeof AppRoute
        }
        '/app/parametrizacion': {
            id: '/app/parametrizacion'
            path: '/parametrizacion'
            fullPath: '/app/parametrizacion'
            preLoaderRoute: typeof AppParametrizacionRouteImport
            parentRoute: typeof AppRoute
        }
        '/app/panel-admin': {
            id: '/app/panel-admin'
            path: '/panel-admin'
            fullPath: '/app/panel-admin'
            preLoaderRoute: typeof AppPanelAdminRouteImport
            parentRoute: typeof AppRoute
        }/*
        '/app/notificaciones': {
            id: '/app/notificaciones'
            path: '/notificaciones'
            fullPath: '/app/notificaciones'
            preLoaderRoute: typeof AppNotificacionesRouteImport
            parentRoute: typeof AppRoute
        }*/
        '/app/inicio': {
            id: '/app/inicio'
            path: '/inicio'
            fullPath: '/app/inicio'
            preLoaderRoute: typeof AppInicioRouteImport
            parentRoute: typeof AppRoute
        }
        '/app/gestion-documentos': {
            id: '/app/gestion-documentos'
            path: '/gestion-documentos'
            fullPath: '/app/gestion-documentos'
            preLoaderRoute: typeof AppGestionDocumentosRouteImport
            parentRoute: typeof AppRoute
        }
        '/app/documentos': {
            id: '/app/documentos'
            path: '/documentos'
            fullPath: '/app/documentos'
            preLoaderRoute: typeof AppDocumentosRouteImport
            parentRoute: typeof AppRoute
        }
        '/app/cambiar-contrasena': {
            id: '/app/cambiar-contrasena'
            path: '/cambiar-contrasena'
            fullPath: '/app/cambiar-contrasena'
            preLoaderRoute: typeof AppCambiarContrasenaRouteImport
            parentRoute: typeof AppRoute
        }
        '/app/documento/$id': {
            id: '/app/documento/$id'
            path: '/documento/$id'
            fullPath: '/app/documento/$id'
            preLoaderRoute: typeof AppDocumentoIdRouteImport
            parentRoute: typeof AppRoute
        }
        '/app/documento/$id/editar': {
            id: '/app/documento/$id/editar'
            path: '/documento/$id/editar'
            fullPath: '/app/documento/$id/editar'
            preLoaderRoute: typeof AppDocumentoIdEditarRouteImport
            parentRoute: typeof AppRoute
        }
        '/app/documento/$id/actualizar': {
            id: '/app/documento/$id/actualizar'
            path: '/documento/$id/actualizar'
            fullPath: '/app/documento/$id/actualizar'
            preLoaderRoute: typeof AppDocumentoIdActualizarRouteImport
            parentRoute: typeof AppRoute
        }
    }
}

interface AppRouteChildren {
    AppDocumentosRoute: typeof AppDocumentosRoute
    AppGestionDocumentosRoute: typeof AppGestionDocumentosRoute
    AppInicioRoute: typeof AppInicioRoute
 //   AppNotificacionesRoute: typeof AppNotificacionesRoute
    AppPanelAdminRoute: typeof AppPanelAdminRoute
    AppParametrizacionRoute: typeof AppParametrizacionRoute
    AppPublicarRoute: typeof AppPublicarRoute
    AppUsuariosRoute: typeof AppUsuariosRoute
    AppCambiarContrasenaRoute: typeof AppCambiarContrasenaRoute
    AppDocumentoIdRoute: typeof AppDocumentoIdRoute
    AppDocumentoIdEditarRoute: typeof AppDocumentoIdEditarRoute
    AppDocumentoIdActualizarRoute: typeof AppDocumentoIdActualizarRoute
}

const AppRouteChildren: AppRouteChildren = {
    AppDocumentosRoute: AppDocumentosRoute,
    AppGestionDocumentosRoute: AppGestionDocumentosRoute,
    AppInicioRoute: AppInicioRoute,
//    AppNotificacionesRoute: AppNotificacionesRoute,
    AppPanelAdminRoute: AppPanelAdminRoute,
    AppParametrizacionRoute: AppParametrizacionRoute,
    AppPublicarRoute: AppPublicarRoute,
    AppUsuariosRoute: AppUsuariosRoute,
    AppCambiarContrasenaRoute: AppCambiarContrasenaRoute,
    AppDocumentoIdRoute: AppDocumentoIdRoute,
    AppDocumentoIdEditarRoute: AppDocumentoIdEditarRoute,
    AppDocumentoIdActualizarRoute: AppDocumentoIdActualizarRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()
