-- ============================================================
-- V1: roles, areas, usuarios, usuario_area
-- Orden por dependencias: roles -> areas -> usuarios -> usuario_area
-- ============================================================

-- ------------------------------------------------------------
-- 1. roles
-- ------------------------------------------------------------
CREATE TABLE roles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(50)  NOT NULL,
    descripcion         VARCHAR(255),
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_roles_nombre UNIQUE (nombre),
    CONSTRAINT chk_roles_nombre
        CHECK (nombre IN ('ADMINISTRADOR', 'JEFE_AREA', 'ADMINISTRATIVO'))
);

-- ------------------------------------------------------------
-- 2. areas
-- ------------------------------------------------------------
CREATE TABLE areas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(20)  NOT NULL,
    nombre              VARCHAR(100) NOT NULL,
    descripcion         VARCHAR(255),
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Unicidad case-insensitive de codigo y nombre (indices funcionales con LOWER)
CREATE UNIQUE INDEX uq_areas_codigo_lower ON areas (LOWER(codigo));
CREATE UNIQUE INDEX uq_areas_nombre_lower ON areas (LOWER(nombre));

-- ------------------------------------------------------------
-- 3. usuarios
-- ------------------------------------------------------------
CREATE TABLE usuarios (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres                     VARCHAR(100) NOT NULL,
    apellidos                   VARCHAR(100) NOT NULL,
    correo                      VARCHAR(150) NOT NULL,
    password_hash               VARCHAR(255) NOT NULL,
    rol_id                      BIGINT       NOT NULL,
    estado                      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVO',
    password_temporal           BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_envio_credenciales    TIMESTAMP,
    fecha_creacion              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuarios_rol
        FOREIGN KEY (rol_id) REFERENCES roles (id),
    CONSTRAINT chk_usuarios_estado
        CHECK (estado IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO'))
);

-- Unicidad case-insensitive de correo
CREATE UNIQUE INDEX uq_usuarios_correo_lower ON usuarios (LOWER(correo));

-- ------------------------------------------------------------
-- 4. usuario_area
-- ------------------------------------------------------------
CREATE TABLE usuario_area (
    usuario_id       BIGINT    NOT NULL,
    area_id          BIGINT    NOT NULL,
    es_principal     BOOLEAN   NOT NULL DEFAULT FALSE,
    fecha_asignacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuario_area PRIMARY KEY (usuario_id, area_id),
    CONSTRAINT fk_usuario_area_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_usuario_area_area
        FOREIGN KEY (area_id) REFERENCES areas (id)
);

-- Un usuario nunca puede tener mas de un area principal
CREATE UNIQUE INDEX uq_usuario_area_principal
    ON usuario_area (usuario_id)
    WHERE es_principal = TRUE;

-- ------------------------------------------------------------
-- 5. Datos iniciales obligatorios de roles
-- ------------------------------------------------------------
INSERT INTO roles (nombre, descripcion) VALUES
    ('ADMINISTRADOR', 'Rol con permisos administrativos completos del sistema'),
    ('JEFE_AREA',      'Rol responsable de la gestion documental de un area'),
    ('ADMINISTRATIVO', 'Rol operativo para la gestion documental cotidiana');
