-- ============================================================
-- V2: eliminar columnas obsoletas de usuarios + crear
--     categorias, tipos_documento, documentos, documento_area,
--     versiones_documento
-- Orden por dependencias: usuarios (alter) -> categorias ->
--     tipos_documento -> documentos -> documento_area ->
--     versiones_documento
-- RIESGO: los DROP COLUMN de usuarios son irreversibles. No hay
-- FKs ni indices dependientes de esas columnas (verificado en V1),
-- pero en un entorno con datos reales esos valores se pierden
-- para siempre al aplicar esta migracion.
-- ============================================================

-- ------------------------------------------------------------
-- 1. usuarios: eliminar columnas de password temporal
-- ------------------------------------------------------------
ALTER TABLE usuarios DROP COLUMN IF EXISTS password_temporal;
ALTER TABLE usuarios DROP COLUMN IF EXISTS fecha_envio_credenciales;

-- ------------------------------------------------------------
-- 2. categorias
-- ------------------------------------------------------------
CREATE TABLE categorias (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(100) NOT NULL,
    descripcion         VARCHAR(255),
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Unicidad case-insensitive de nombre
CREATE UNIQUE INDEX uq_categorias_nombre_lower ON categorias (LOWER(nombre));

-- ------------------------------------------------------------
-- 3. tipos_documento
-- ------------------------------------------------------------
CREATE TABLE tipos_documento (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(100) NOT NULL,
    descripcion         VARCHAR(255),
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Unicidad case-insensitive de nombre
CREATE UNIQUE INDEX uq_tipos_documento_nombre_lower ON tipos_documento (LOWER(nombre));

-- ------------------------------------------------------------
-- 4. documentos
-- ------------------------------------------------------------
CREATE TABLE documentos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(50)  NOT NULL,
    titulo              VARCHAR(200) NOT NULL,
    descripcion         VARCHAR(500),
    categoria_id        BIGINT       NOT NULL,
    tipo_documento_id   BIGINT       NOT NULL,
    creado_por          BIGINT       NOT NULL,
    estado              VARCHAR(20)  NOT NULL DEFAULT 'PUBLICADO',
    es_global           BOOLEAN      NOT NULL DEFAULT FALSE,
    fecha_creacion      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_documentos_categoria
        FOREIGN KEY (categoria_id) REFERENCES categorias (id),
    CONSTRAINT fk_documentos_tipo_documento
        FOREIGN KEY (tipo_documento_id) REFERENCES tipos_documento (id),
    CONSTRAINT fk_documentos_creado_por
        FOREIGN KEY (creado_por) REFERENCES usuarios (id),
    CONSTRAINT chk_documentos_estado
        CHECK (estado IN ('PUBLICADO', 'INACTIVO', 'OBSOLETO'))
);

-- Unicidad case-insensitive de codigo
CREATE UNIQUE INDEX uq_documentos_codigo_lower ON documentos (LOWER(codigo));

-- ------------------------------------------------------------
-- 5. documento_area
-- ------------------------------------------------------------
CREATE TABLE documento_area (
    id_documento_area BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id      BIGINT    NOT NULL,
    area_id           BIGINT    NOT NULL,
    es_principal      BOOLEAN   NOT NULL DEFAULT FALSE,
    fecha_asignacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_documento_area_documento
        FOREIGN KEY (documento_id) REFERENCES documentos (id),
    CONSTRAINT fk_documento_area_area
        FOREIGN KEY (area_id) REFERENCES areas (id),
    CONSTRAINT uq_documento_area UNIQUE (documento_id, area_id)
);

-- Un documento nunca puede tener mas de un area principal
CREATE UNIQUE INDEX uq_documento_area_principal
    ON documento_area (documento_id)
    WHERE es_principal = TRUE;

-- ------------------------------------------------------------
-- 6. versiones_documento
-- ------------------------------------------------------------
CREATE TABLE versiones_documento (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id                BIGINT       NOT NULL,
    numero_version              INTEGER      NOT NULL,
    nombre_archivo_original     VARCHAR(255) NOT NULL,
    nombre_archivo_almacenado   VARCHAR(255) NOT NULL,
    ruta_archivo                VARCHAR(500) NOT NULL,
    tipo_mime                   VARCHAR(150) NOT NULL,
    tamano_bytes                BIGINT       NOT NULL,
    descripcion_cambio          VARCHAR(500) NOT NULL,
    fecha_publicacion           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    publicado_por               BIGINT       NOT NULL,
    vigente                     BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_versiones_documento_documento
        FOREIGN KEY (documento_id) REFERENCES documentos (id),
    CONSTRAINT fk_versiones_documento_publicado_por
        FOREIGN KEY (publicado_por) REFERENCES usuarios (id),
    CONSTRAINT uq_versiones_documento_numero UNIQUE (documento_id, numero_version)
);

-- Solo puede existir una version vigente por documento
CREATE UNIQUE INDEX uq_versiones_documento_vigente
    ON versiones_documento (documento_id)
    WHERE vigente = TRUE;
